#!/usr/bin/env python3
"""
Example TRF Analysis with Eelbrain

Demonstrates how to use the extracted features (prosody, TRPs) for
Temporal Response Function (TRF) modeling of MEG data.

This example shows:
1. Loading feature tables from the pipeline
2. Aligning features to MEG time
3. Creating continuous and event predictors
4. Fitting TRFs with eelbrain's boosting
5. Testing significance and visualizing results
"""

import numpy as np
import pandas as pd
import mne
from pathlib import Path
import json
import matplotlib.pyplot as plt
from scipy.interpolate import interp1d

# Try to import eelbrain (optional - install if needed)
try:
    import eelbrain
    HAS_EELBRAIN = True
except ImportError:
    HAS_EELBRAIN = False
    print("Warning: eelbrain not installed. This script requires eelbrain for TRF modeling.")
    print("Install with: pip install eelbrain")


def load_pipeline_features(subject: str, run: int, base_dir: Path):
    """
    Load all features generated by the turn-taking pipeline.

    Parameters
    ----------
    subject : str
        Subject ID (e.g., 'sub-01')
    run : int
        Run number (1-5)
    base_dir : Path
        Base directory of the pipeline project

    Returns
    -------
    features : dict
        Dictionary with all loaded features:
        - sync_params: Synchronization parameters
        - transcript: Word-level transcript
        - turns: Turn-level segmentation
        - prosody: Frame-by-frame prosodic features
        - pauses: Pause detections
        - speech_rate: Local speech rate
        - trp_features: TRP candidates
    """
    feature_dir = base_dir / "outputs" / "features" / subject / f"run-{run:02d}"

    print(f"Loading features for {subject}, run {run}")
    print(f"Directory: {feature_dir}")

    features = {}

    # Load sync params (JSON)
    with open(feature_dir / "sync_params.json") as f:
        features["sync_params"] = json.load(f)

    # Load all CSV files
    features["transcript"] = pd.read_csv(feature_dir / "transcript.csv")
    features["turns"] = pd.read_csv(feature_dir / "turns.csv")
    features["prosody"] = pd.read_csv(feature_dir / "prosody.csv")
    features["pauses"] = pd.read_csv(feature_dir / "pauses.csv")
    features["speech_rate"] = pd.read_csv(feature_dir / "speech_rate.csv")
    features["trp_features"] = pd.read_csv(feature_dir / "trp_features.csv")

    print(f"✓ Loaded {len(features['prosody'])} prosody frames")
    print(f"✓ Loaded {len(features['turns'])} turns")
    print(f"✓ Loaded {len(features['pauses'])} pauses")
    print(f"✓ Loaded {len(features['trp_features'])} TRP candidates")

    return features


def align_features_to_meg(features: dict, meg_times: np.ndarray):
    """
    Align all features to MEG sampling rate and timebase.

    Parameters
    ----------
    features : dict
        Features from load_pipeline_features()
    meg_times : np.ndarray
        MEG time points (seconds)

    Returns
    -------
    meg_features : dict
        Dictionary with MEG-aligned features:
        - f0: Fundamental frequency (Hz)
        - intensity: Intensity (dB)
        - energy: RMS energy
        - speech_rate: Words per second
        - trp_events: Binary event regressor for TRPs
        - turn_onsets: Binary event regressor for turn starts
    """
    print("\nAligning features to MEG timebase...")

    # Get prosody DataFrame
    prosody = features["prosody"]

    # Prosody is in external audio time - convert to MEG time
    offset_s = features["sync_params"]["initial_offset_s"]
    prosody_times_meg = prosody["time"].values - offset_s

    print(f"  Time offset: {offset_s:.3f}s (external audio starts before MEG)")
    print(f"  Prosody time range (MEG): {prosody_times_meg.min():.1f}s to {prosody_times_meg.max():.1f}s")
    print(f"  MEG time range: {meg_times.min():.1f}s to {meg_times.max():.1f}s")

    meg_features = {}

    # === Continuous Features (interpolate to MEG sampling rate) ===

    # F0 (pitch)
    f0_interp = interp1d(
        prosody_times_meg,
        prosody["f0_smooth"].values,
        kind="linear",
        bounds_error=False,
        fill_value=np.nan
    )
    meg_features["f0"] = f0_interp(meg_times)

    # Intensity
    intensity_interp = interp1d(
        prosody_times_meg,
        prosody["intensity"].values,
        kind="linear",
        bounds_error=False,
        fill_value=0
    )
    meg_features["intensity"] = intensity_interp(meg_times)

    # Energy
    energy_interp = interp1d(
        prosody_times_meg,
        prosody["energy"].values,
        kind="linear",
        bounds_error=False,
        fill_value=0
    )
    meg_features["energy"] = energy_interp(meg_times)

    # Speech rate (piecewise constant)
    speech_rate_df = features["speech_rate"]
    speech_rate_times_meg = speech_rate_df["time"].values - offset_s
    speech_rate_interp = interp1d(
        speech_rate_times_meg,
        speech_rate_df["words_per_second"].values,
        kind="previous",  # Piecewise constant
        bounds_error=False,
        fill_value=0
    )
    meg_features["speech_rate"] = speech_rate_interp(meg_times)

    # === Event Features (impulse regressors) ===

    # TRP events
    trp_events = np.zeros(len(meg_times))
    trp_df = features["trp_features"]
    trp_times_meg = trp_df["time"].values - offset_s

    for trp_time in trp_times_meg:
        if meg_times.min() <= trp_time <= meg_times.max():
            idx = np.argmin(np.abs(meg_times - trp_time))
            trp_events[idx] = 1.0

    meg_features["trp_events"] = trp_events

    # Turn onset events
    turn_onsets = np.zeros(len(meg_times))
    turns_df = features["turns"]

    # Convert turn start times to MEG time
    if "start_meg" in turns_df.columns:
        turn_start_times = turns_df["start_meg"].values
    else:
        turn_start_times = turns_df["start"].values - offset_s

    for turn_time in turn_start_times:
        if meg_times.min() <= turn_time <= meg_times.max():
            idx = np.argmin(np.abs(meg_times - turn_time))
            turn_onsets[idx] = 1.0

    meg_features["turn_onsets"] = turn_onsets

    print(f"✓ Aligned {len(meg_features)} feature types to MEG")
    print(f"  - F0: {np.sum(~np.isnan(meg_features['f0']))} voiced samples")
    print(f"  - TRP events: {int(np.sum(trp_events))} events")
    print(f"  - Turn onsets: {int(np.sum(turn_onsets))} events")

    return meg_features


def create_eelbrain_predictors(meg_features: dict, meg_times: np.ndarray, sfreq: float):
    """
    Create eelbrain NDVar objects for TRF modeling.

    Parameters
    ----------
    meg_features : dict
        MEG-aligned features from align_features_to_meg()
    meg_times : np.ndarray
        MEG time points
    sfreq : float
        MEG sampling frequency (Hz)

    Returns
    -------
    predictors : dict
        Dictionary of eelbrain NDVar objects ready for boosting
    """
    if not HAS_EELBRAIN:
        print("ERROR: eelbrain not installed. Cannot create predictors.")
        return None

    print("\nCreating eelbrain NDVar predictors...")

    # Create time dimension
    time_dim = eelbrain.UTS(0, 1/sfreq, len(meg_times))

    predictors = {}

    # Continuous predictors
    predictors["f0"] = eelbrain.NDVar(
        meg_features["f0"],
        dims=(time_dim,),
        name="F0"
    )

    predictors["intensity"] = eelbrain.NDVar(
        meg_features["intensity"],
        dims=(time_dim,),
        name="Intensity"
    )

    predictors["energy"] = eelbrain.NDVar(
        meg_features["energy"],
        dims=(time_dim,),
        name="Energy"
    )

    predictors["speech_rate"] = eelbrain.NDVar(
        meg_features["speech_rate"],
        dims=(time_dim,),
        name="SpeechRate"
    )

    # Event predictors
    predictors["trp"] = eelbrain.NDVar(
        meg_features["trp_events"],
        dims=(time_dim,),
        name="TRP"
    )

    predictors["turns"] = eelbrain.NDVar(
        meg_features["turn_onsets"],
        dims=(time_dim,),
        name="TurnOnset"
    )

    print(f"✓ Created {len(predictors)} eelbrain predictors")

    return predictors


def example_trf_analysis(subject: str, run: int, meg_source_stc, base_dir: Path):
    """
    Complete example of TRF analysis pipeline.

    Parameters
    ----------
    subject : str
        Subject ID
    run : int
        Run number
    meg_source_stc : SourceEstimate or NDVar
        Source-space MEG data (e.g., from beamformer)
    base_dir : Path
        Pipeline base directory

    Returns
    -------
    trf_results : dict
        TRF model results
    """
    if not HAS_EELBRAIN:
        print("ERROR: This example requires eelbrain")
        return None

    print("="*70)
    print("EXAMPLE TRF ANALYSIS WITH TURN-TAKING FEATURES")
    print("="*70)

    # 1. Load features
    features = load_pipeline_features(subject, run, base_dir)

    # 2. Get MEG times (from your MEG data)
    # For this example, we'll create a mock time array
    # In real analysis, get this from your SourceEstimate or Raw object
    meg_sfreq = features["sync_params"]["meg_sfreq"]
    meg_duration = features["sync_params"]["meg_duration_s"]
    meg_times = np.arange(0, meg_duration, 1/meg_sfreq)

    print(f"\nMEG data: {meg_duration:.1f}s at {meg_sfreq:.0f} Hz ({len(meg_times)} samples)")

    # 3. Align features to MEG
    meg_features = align_features_to_meg(features, meg_times)

    # 4. Create eelbrain predictors
    predictors = create_eelbrain_predictors(meg_features, meg_times, meg_sfreq)

    # 5. Fit TRF (example with synthetic MEG data)
    print("\n" + "="*70)
    print("TRF MODELING (Example)")
    print("="*70)

    # NOTE: Replace this with your actual MEG source data
    # meg_source_stc should be an eelbrain NDVar with dimensions (source, time)
    # or an MNE SourceEstimate that you convert to NDVar

    print("\nTo fit TRF with real data, use:")
    print("""
    # Load your beamformed source data
    stc = mne.read_source_estimate('path/to/your/stc')

    # Convert to eelbrain NDVar
    meg_ndvar = eelbrain.load.mne.stc_ndvar(stc, subject='fsaverage', ...)

    # Fit TRF
    trf = eelbrain.boosting(
        meg_ndvar,                    # Neural response (dependent variable)
        [predictors['f0'],            # Predictors (independent variables)
         predictors['intensity'],
         predictors['trp']],
        tstart=-0.1,                  # TRF start time (before event)
        tstop=0.5,                    # TRF end time (after event)
        basis=0.050,                  # Basis function width (50ms)
        partitions=5,                 # Cross-validation folds
        test=1,                       # Partition to use for testing
        selective_stopping=True,      # Early stopping per predictor
    )

    # Test significance
    results = eelbrain.testnd.corr(
        trf.r,                        # Model correlation
        alpha=0.05,
        samples=10000,                # Permutation samples
        pmin=0.05,                    # Cluster-forming threshold
    )

    # Plot TRFs
    eelbrain.plot.brain.butterfly(trf.h_scaled['F0'])
    eelbrain.plot.brain.butterfly(trf.h_scaled['TRP'])
    """)

    return {
        "features": features,
        "meg_features": meg_features,
        "predictors": predictors,
    }


def simple_correlation_analysis(subject: str, run: int, base_dir: Path):
    """
    Simple example: correlate prosodic features without full TRF.

    Useful for validating features before running heavy TRF models.
    """
    print("="*70)
    print("SIMPLE FEATURE VALIDATION")
    print("="*70)

    features = load_pipeline_features(subject, run, base_dir)
    prosody = features["prosody"]

    # Basic statistics
    print("\nProsodic Feature Statistics:")
    print(f"  F0 range: {prosody['f0'].min():.1f} - {prosody['f0'].max():.1f} Hz")
    print(f"  F0 mean (voiced): {prosody['f0'].mean():.1f} Hz")
    print(f"  Voicing: {prosody['is_voiced'].mean()*100:.1f}%")
    print(f"  Mean intensity: {prosody['intensity'].mean():.1f} dB")
    print(f"  Mean energy: {prosody['energy'].mean():.4f}")

    # Speech rate
    speech_rate = features["speech_rate"]
    print(f"\nSpeech Rate:")
    print(f"  Mean: {speech_rate['words_per_second'].mean():.2f} words/s")
    print(f"  Range: {speech_rate['words_per_second'].min():.2f} - {speech_rate['words_per_second'].max():.2f}")

    # Turns
    turns = features["turns"]
    print(f"\nTurn Statistics:")
    print(f"  Total turns: {len(turns)}")
    print(f"  Mean duration: {turns['duration'].mean():.2f}s")
    print(f"  Mean words per turn: {turns['n_words'].mean():.1f}")

    # TRPs
    trps = features["trp_features"]
    print(f"\nTRP Statistics:")
    print(f"  Total TRP candidates: {len(trps)}")
    if len(trps) > 0:
        print(f"  Mean pause duration: {trps['duration'].mean():.2f}s")
        print(f"  Mean F0 slope: {trps['f0_slope'].mean():.2f} Hz/s")
        print(f"  Segment-final: {trps['is_segment_final'].sum()}/{len(trps)}")

    # Plot some features
    fig, axes = plt.subplots(3, 1, figsize=(12, 8), sharex=True)

    # F0
    axes[0].plot(prosody["time"], prosody["f0"], alpha=0.7, linewidth=0.5)
    axes[0].set_ylabel("F0 (Hz)")
    axes[0].set_title(f"Prosodic Features - {subject} Run {run}")
    axes[0].grid(True, alpha=0.3)

    # Intensity
    axes[1].plot(prosody["time"], prosody["intensity"], alpha=0.7, linewidth=0.5, color="orange")
    axes[1].set_ylabel("Intensity (dB)")
    axes[1].grid(True, alpha=0.3)

    # Energy
    axes[2].plot(prosody["time"], prosody["energy"], alpha=0.7, linewidth=0.5, color="green")
    axes[2].set_ylabel("Energy (RMS)")
    axes[2].set_xlabel("Time (s)")
    axes[2].grid(True, alpha=0.3)

    # Mark TRPs
    for _, trp in trps.iterrows():
        for ax in axes:
            ax.axvline(trp["time"], color="red", alpha=0.5, linestyle="--", linewidth=1)

    plt.tight_layout()

    output_path = base_dir / "outputs" / "features" / subject / f"run-{run:02d}" / "feature_validation.png"
    plt.savefig(output_path, dpi=150, bbox_inches="tight")
    print(f"\n✓ Saved feature validation plot: {output_path}")

    return features


def main():
    """Run example analysis."""
    import argparse

    parser = argparse.ArgumentParser(description="Example TRF analysis with turn-taking features")
    parser.add_argument("--subject", type=str, default="sub-01", help="Subject ID")
    parser.add_argument("--run", type=int, default=1, help="Run number")
    parser.add_argument("--validate-only", action="store_true",
                       help="Only run feature validation (no TRF)")

    args = parser.parse_args()

    # Base directory
    base_dir = Path(__file__).parent.parent

    if args.validate_only:
        # Just validate features
        features = simple_correlation_analysis(args.subject, args.run, base_dir)
        print("\n✓ Feature validation complete!")
        print("  View the plots in outputs/features/{subject}/run-{run:02d}/")
    else:
        # Full TRF example
        if HAS_EELBRAIN:
            results = example_trf_analysis(
                args.subject,
                args.run,
                meg_source_stc=None,  # Replace with your MEG data
                base_dir=base_dir
            )
            print("\n✓ TRF example complete!")
            print("  Replace meg_source_stc with your actual beamformer output to run real TRF.")
        else:
            print("\nERROR: eelbrain not installed.")
            print("Install with: pip install eelbrain")
            print("\nRunning feature validation instead...")
            features = simple_correlation_analysis(args.subject, args.run, base_dir)


if __name__ == "__main__":
    main()
